// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TwitterUalaChallenge.Infrastructure.Persistence;

#nullable disable

namespace TwitterUalaChallenge.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TwitterUalaChallengeDbContext))]
    partial class TwitterUalaChallengeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("TwitterUalaChallenge")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TwitterUalaChallenge.Domain.Entities.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("pk_test");

                    b.HasIndex("Description")
                        .IsUnique()
                        .HasDatabaseName("IX_Test_Description_Unique");

                    b.ToTable("Test", "TwitterUalaChallenge");
                });
#pragma warning restore 612, 618
        }
    }
}
